CREATE TABLE IF NOT EXISTS regular_expressions (
    id SERIAL PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    captured_injections INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS detected_injections (
    id SERIAL PRIMARY KEY,
    description TEXT UNIQUE NOT NULL,
    detected_times INTEGER NOT NULL DEFAULT 0
);

INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (1, '(\%27)|(\'')|(--[^\r\n]*)|(;%00)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (2, '((\%3D)|(=))[^\n]*((\%27)|(\'')|(\-\-)|(\%3B)|(;))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (3, '((\%27)|(\''))((\%6F)|o|(\%4F))((\%72)|r|(\%52))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (4, '(\W)(and|or)\s*\d+\s*(=|\>\=|\<\=|\>\\<|\<|\>)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (5, '((\%27)|(\''))UNION', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (6, '([\s\(\)])(select|drop|insert|delete|update|create|alter)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (7, '([\s\(\)])(exec|execute)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (8, '(\%20and|\+and|&&|\&\&)', 0);
/*INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (9, '(\%27)|(\'')|(--[^\r\n]*)|(;%00)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (10, '((\%3D)|(=))[^\n]*((\%27)|(\'')|(\-\-)|(\%3B)|(;))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (11, '((\%27)|(\''))((\%6F)|o|(\%4F))((\%72)|r|(\%52))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (12, '(\W)(and|or)\s*\d+\s*(=|\>\=|\<\=|\>\\<|\<|\>)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (13, '((\%27)|(\''))UNION', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (14, '([\s\(\)])(select|drop|insert|delete|update|create|alter)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (15, '([\s\(\)])(exec|execute)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (16, '(\%20and|\+and|&&|\&\&)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (17, '(\%27)|(\'')|(--[^\r\n]*)|(;%00)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (18, '((\%3D)|(=))[^\n]*((\%27)|(\'')|(\-\-)|(\%3B)|(;))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (19, '((\%27)|(\''))((\%6F)|o|(\%4F))((\%72)|r|(\%52))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (20, '(\W)(and|or)\s*\d+\s*(=|\>\=|\<\=|\>\\<|\<|\>)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (21, '((\%27)|(\''))UNION', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (22, '([\s\(\)])(select|drop|insert|delete|update|create|alter)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (23, '([\s\(\)])(exec|execute)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (24, '(\%20and|\+and|&&|\&\&)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (25, '(\%27)|(\'')|(--[^\r\n]*)|(;%00)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (26, '((\%3D)|(=))[^\n]*((\%27)|(\'')|(\-\-)|(\%3B)|(;))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (27, '((\%27)|(\''))((\%6F)|o|(\%4F))((\%72)|r|(\%52))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (28, '(\W)(and|or)\s*\d+\s*(=|\>\=|\<\=|\>\\<|\<|\>)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (29, '((\%27)|(\''))UNION', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (30, '([\s\(\)])(select|drop|insert|delete|update|create|alter)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (31, '([\s\(\)])(exec|execute)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (32, '(\%20and|\+and|&&|\&\&)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (33, '(\%27)|(\'')|(--[^\r\n]*)|(;%00)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (34, '((\%3D)|(=))[^\n]*((\%27)|(\'')|(\-\-)|(\%3B)|(;))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (35, '((\%27)|(\''))((\%6F)|o|(\%4F))((\%72)|r|(\%52))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (36, '(\W)(and|or)\s*\d+\s*(=|\>\=|\<\=|\>\\<|\<|\>)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (37, '((\%27)|(\''))UNION', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (38, '([\s\(\)])(select|drop|insert|delete|update|create|alter)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (39, '([\s\(\)])(exec|execute)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (40, '(\%20and|\+and|&&|\&\&)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (41, '(\%27)|(\'')|(--[^\r\n]*)|(;%00)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (42, '((\%3D)|(=))[^\n]*((\%27)|(\'')|(\-\-)|(\%3B)|(;))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (43, '((\%27)|(\''))((\%6F)|o|(\%4F))((\%72)|r|(\%52))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (44, '(\W)(and|or)\s*\d+\s*(=|\>\=|\<\=|\>\\<|\<|\>)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (45, '((\%27)|(\''))UNION', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (46, '([\s\(\)])(select|drop|insert|delete|update|create|alter)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (47, '([\s\(\)])(exec|execute)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (48, '(\%20and|\+and|&&|\&\&)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (49, '(\%27)|(\'')|(--[^\r\n]*)|(;%00)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (50, '((\%3D)|(=))[^\n]*((\%27)|(\'')|(\-\-)|(\%3B)|(;))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (51, '((\%27)|(\''))((\%6F)|o|(\%4F))((\%72)|r|(\%52))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (52, '(\W)(and|or)\s*\d+\s*(=|\>\=|\<\=|\>\\<|\<|\>)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (53, '((\%27)|(\''))UNION', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (54, '([\s\(\)])(select|drop|insert|delete|update|create|alter)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (55, '([\s\(\)])(exec|execute)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (56, '(\%20and|\+and|&&|\&\&)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (57, '(\%27)|(\'')|(--[^\r\n]*)|(;%00)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (58, '((\%3D)|(=))[^\n]*((\%27)|(\'')|(\-\-)|(\%3B)|(;))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (59, '((\%27)|(\''))((\%6F)|o|(\%4F))((\%72)|r|(\%52))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (60, '(\W)(and|or)\s*\d+\s*(=|\>\=|\<\=|\>\\<|\<|\>)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (61, '((\%27)|(\''))UNION', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (62, '([\s\(\)])(select|drop|insert|delete|update|create|alter)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (63, '([\s\(\)])(exec|execute)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (64, '(\%20and|\+and|&&|\&\&)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (65, '(\%27)|(\'')|(--[^\r\n]*)|(;%00)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (66, '((\%3D)|(=))[^\n]*((\%27)|(\'')|(\-\-)|(\%3B)|(;))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (67, '((\%27)|(\''))((\%6F)|o|(\%4F))((\%72)|r|(\%52))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (68, '(\W)(and|or)\s*\d+\s*(=|\>\=|\<\=|\>\\<|\<|\>)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (69, '((\%27)|(\''))UNION', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (70, '([\s\(\)])(select|drop|insert|delete|update|create|alter)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (71, '([\s\(\)])(exec|execute)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (72, '(\%20and|\+and|&&|\&\&)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (73, '(\%27)|(\'')|(--[^\r\n]*)|(;%00)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (74, '((\%3D)|(=))[^\n]*((\%27)|(\'')|(\-\-)|(\%3B)|(;))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (75, '((\%27)|(\''))((\%6F)|o|(\%4F))((\%72)|r|(\%52))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (76, '(\W)(and|or)\s*\d+\s*(=|\>\=|\<\=|\>\\<|\<|\>)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (77, '((\%27)|(\''))UNION', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (78, '([\s\(\)])(select|drop|insert|delete|update|create|alter)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (79, '([\s\(\)])(exec|execute)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (80, '(\%20and|\+and|&&|\&\&)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (81, '(\%27)|(\'')|(--[^\r\n]*)|(;%00)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (82, '((\%3D)|(=))[^\n]*((\%27)|(\'')|(\-\-)|(\%3B)|(;))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (83, '((\%27)|(\''))((\%6F)|o|(\%4F))((\%72)|r|(\%52))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (84, '(\W)(and|or)\s*\d+\s*(=|\>\=|\<\=|\>\\<|\<|\>)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (85, '((\%27)|(\''))UNION', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (86, '([\s\(\)])(select|drop|insert|delete|update|create|alter)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (87, '([\s\(\)])(exec|execute)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (88, '(\%20and|\+and|&&|\&\&)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (89, '(\%27)|(\'')|(--[^\r\n]*)|(;%00)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (90, '((\%3D)|(=))[^\n]*((\%27)|(\'')|(\-\-)|(\%3B)|(;))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (91, '((\%27)|(\''))((\%6F)|o|(\%4F))((\%72)|r|(\%52))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (92, '(\W)(and|or)\s*\d+\s*(=|\>\=|\<\=|\>\\<|\<|\>)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (93, '((\%27)|(\''))UNION', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (94, '([\s\(\)])(select|drop|insert|delete|update|create|alter)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (95, '([\s\(\)])(exec|execute)([\s\(\)])', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (96, '(\%20and|\+and|&&|\&\&)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (97, '(\%27)|(\'')|(--[^\r\n]*)|(;%00)', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (98, '((\%3D)|(=))[^\n]*((\%27)|(\'')|(\-\-)|(\%3B)|(;))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (99, '((\%27)|(\''))((\%6F)|o|(\%4F))((\%72)|r|(\%52))', 0);
INSERT INTO "regular_expressions" ("id", "description", "captured_injections") VALUES (100, '(\W)(and|or)\s*\d+\s*(=|\>\=|\<\=|\>\\<|\<|\>)', 0);*/